//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\CarRental.mdf" +
            ";Integrated Security=True")]
        public string CarRentalConnectionString {
            get {
                return ((string)(this["CarRentalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=""C:\USERS\IDRIS\DOCUMENTS\FTMK\SEM 4\EVENT-DRIVEN PROGRAMMING\CAR-RENTAL-SYSTEM\CAR RENTAL SYSTEM\BIN\DEBUG\CARRENTAL.MDF"";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_IDRIS_DOCUMENTS_FTMK_SEM_4_EVENT_DRIVEN_PROGRAMMING_CAR_RENTAL_SYSTEM_CAR_RENTAL_SYSTEM_BIN_DEBUG_CARRENTAL_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_IDRIS_DOCUMENTS_FTMK_SEM_4_EVENT_DRIVEN_PROGRAMMING_CAR_RENTAL_SYSTEM_CA" +
                    "R_RENTAL_SYSTEM_BIN_DEBUG_CARRENTAL_MDFConnectionString"]));
            }
        }
    }
}
